// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk9rpEw2du2syUEJpttNMZasTW3CcJ6cY',
    appId: '1:1002173485731:web:39dc5ebc6fb00b09e0e516',
    messagingSenderId: '1002173485731',
    projectId: 'perioder',
    authDomain: 'perioder.firebaseapp.com',
    storageBucket: 'perioder.firebasestorage.app',
    measurementId: 'G-V1SPVHWSF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSK0djRO4UHudau3YMnCl4qWvu4_8PtyU',
    appId: '1:1002173485731:android:4d2b903e13706c60e0e516',
    messagingSenderId: '1002173485731',
    projectId: 'perioder',
    storageBucket: 'perioder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOi33UxQBIcVf4PK-puamDlcY2WsN4dRo',
    appId: '1:1002173485731:ios:c741ab93f5f61881e0e516',
    messagingSenderId: '1002173485731',
    projectId: 'perioder',
    storageBucket: 'perioder.firebasestorage.app',
    iosBundleId: 'com.jatuporndev.perioder.perioder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOi33UxQBIcVf4PK-puamDlcY2WsN4dRo',
    appId: '1:1002173485731:ios:c741ab93f5f61881e0e516',
    messagingSenderId: '1002173485731',
    projectId: 'perioder',
    storageBucket: 'perioder.firebasestorage.app',
    iosBundleId: 'com.jatuporndev.perioder.perioder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk9rpEw2du2syUEJpttNMZasTW3CcJ6cY',
    appId: '1:1002173485731:web:0235cc9503fffcbce0e516',
    messagingSenderId: '1002173485731',
    projectId: 'perioder',
    authDomain: 'perioder.firebaseapp.com',
    storageBucket: 'perioder.firebasestorage.app',
    measurementId: 'G-D2MZHXDB40',
  );
}
